global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "localhost"

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Uncomment the following section if you need to using postgres exporter
  # - job_name: postgres
  #   static_configs:
  #     - targets: ["postgres_exporter:9187"]

  # uncomment the following section if you need to using nginx exporter
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx_exporter:9113']